default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: twittter_development
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: twittter_test
  pool: 5
  username: postgres
  password: postgres


production:
  <<: *default
  database: 
  username: 
  password: 
